name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: bank_repo

      # Add your deployment steps here
      # For example, deploying to a hosting service

